---
application.conf:
    ARCHIVE_S3_REGION_NAME: 'ap-northeast-1'
    ARCHIVE_S3_BUCKET_NAME: 'ssp-archive'
    ARCHIVE_PERIOD: 'minutely'
    ARCHIVE_KAFKA_TOPIC: 'ssp-edge-events'
    REPLAY_KAFKA_BROKERS: 'localhost:9092'
    REPLAY_KAFKA_TOPIC: 'ssp-replay-events'
    REPLAY_KAFKA_SERIALIZER_KEY: 'org.apache.kafka.common.serialization.StringSerializer'
    REPLAY_KAFKA_SERIALIZER_VALUE: 'org.apache.kafka.common.serialization.ByteArraySerializer'
    REPLAY_COUCHBASE_CONNECTION_STRING: 'http://localhost:8091'
    REPLAY_COUCHBASE_BUCKET_NAME: 'ssp_replay_offset'
    REPLAY_COUCHBASE_BUCKET_PASSWORD: ''
    REPLAY_COUCHBASE_BUCKET_KEY_PREFIX: 'ro_'

logback.xml:
    INSIDE_LOG_DIR: '/Users/chenshuai/logs'
    LOG_LEVEL: 'DEBUG'
